"""initial_tables

Revision ID: 1f9b2a61b7c4
Revises: 00c6ca338f84
Create Date: 2025-12-22 22:55:12.560140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9b2a61b7c4'
down_revision: Union[str, Sequence[str], None] = '00c6ca338f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_branch_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('branch_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('users_branch_id_fkey'), 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###
