"""Add role to user

Revision ID: 60849fbcf0e8
Revises: caa08bfa8325
Create Date: 2026-01-02 01:20:27.369035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60849fbcf0e8'
down_revision: Union[str, Sequence[str], None] = 'caa08bfa8325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.execute("UPDATE users SET role = 'user'")
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
